[package]
name = "ifnotnow"
version = "0.1.0"
authors = ["Simon Janes <spjanes@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap ="*"
serde = "*"
serde_yaml = "*"
chrono = "*"
